#! /usr/bin/env node

console.log(
  'This script populates some example shoes to your database. Specified database as argument - e.g.: node populatedb "mongodb+srv://cooluser:coolpassword@cluster0.lz91hw2.mongodb.net/inventory_application?retryWrites=true&w=majority"',
);

// Get arguments passed on command line
const userArgs = process.argv.slice(2);

const mongoose = require('mongoose');

const Shirt = require('./models/shirt');
const TShirt = require('./models/tshirt');
const Jean = require('./models/jean');
const Trouser = require('./models/trouser');
const Shoe = require('./models/shoe');
const Sweatshirt = require('./models/sweatshirt');

const shirts = [];
const tshirts = [];
const jeans = [];
const trousers = [];
const shoes = [];
const sweatshirts = [];

mongoose.set('strictQuery', false);

const mongoDB = userArgs[0];

main().catch((err) => console.log(err));

async function main() {
  console.log('Debug: About to connect');
  await mongoose.connect(mongoDB);
  console.log('Debug: Should be connected?');
  await createShirts();
  await createShoes();
  await createJeans();
  await createTrousers();
  await createTShirts();
  await createSweatshirts();
  console.log('Debug: Closing mongoose');
  mongoose.connection.close();
}

async function shoeCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const shoeDetails = { name, imageURL, price, sizes, description, fit };
  const shoe = new Shoe(shoeDetails);
  await shoe.save();
  shoes[index] = shoe;
  console.log(`Added shoe: ${name}`);
}

async function shirtCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const shirtDetails = { name, imageURL, price, sizes, description, fit };

  const shirt = new Shirt(shirtDetails);
  await shirt.save();
  shirts[index] = shirt;
  console.log(`Added shirt: ${name}`);
}

async function jeanCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const jeanDetails = { name, imageURL, price, sizes, description, fit };
  const jean = new Jean(jeanDetails);
  await jean.save();
  jeans[index] = jean;
  console.log(`Added jean: ${name}`);
}

async function trouserCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const trouserDetails = {
    name,
    imageURL,
    price,
    sizes,
    description,
    fit,
  };
  const trouser = new Trouser(trouserDetails);
  await trouser.save();
  trousers[index] = trouser;
  console.log(`Added trouser: ${name}`);
}

async function tshirtCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const tshirtDetails = { name, imageURL, price, sizes, description, fit };
  const tshirt = new TShirt(tshirtDetails);
  await tshirt.save();
  tshirts[index] = tshirt;
  console.log(`Added tshirt: ${name}`);
}

async function sweatshirtCreate(
  index,
  name,
  imageURL,
  price,
  sizes,
  description,
  fit,
) {
  const sweatshirtDetails = {
    name,
    imageURL,
    price,
    sizes,
    description,
    fit,
  };
  const sweatshirt = new Sweatshirt(sweatshirtDetails);
  await sweatshirt.save();
  sweatshirts[index] = sweatshirt;
  console.log(`Added sweatshirt: ${name}`);
}

async function createShoes() {
  console.log('Adding shoes');
  await Promise.all([
    shoeCreate(
      0,
      'Trainers',
      'https://i.imgur.com/8cnyQZG.png',
      'Rs. 2,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers with a padded top edge and a tongue and lacing at the front. Linings and insoles in mesh. Chunky, patterned soles. Height of soles 4.5 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: White/Black, Block-coloured',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      1,
      'Chelsea boots',
      'https://i.imgur.com/izrsEBy.png',
      'Rs. 3,599.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Chelsea boots in soft imitation suede with elastic gores in the sides and a loop at the back. Linings and insoles in imitation leather and cotton canvas. Fluted soles. Heel 2.7 cm.',
      [
        'Heel Height: Low heel',
        'Footwear Style: Chelsea boots',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 3,599.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Boots',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      2,
      'Derby shoes',
      'https://i.imgur.com/x8hHPZ5.png',
      'Rs. 2,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Derby shoes with open lacing at the front. Canvas linings and insoles. Heel 2.5 cm.',
      [
        'Heel Height: Low heel',
        'Footwear Style: Derby shoes',
        'Description: Dark brown, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Smart shoe',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      3,
      'Chunky trainers',
      'https://i.imgur.com/X58X7Jt.png',
      'Rs. 3,599.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers in piqué with imitation suede and imitation leather sections. Padded top edge, a tongue and lacing at the front and a loop at the back. Jersey linings, piqué insoles and chunky rubber soles that are patterned underneath. Height of soles 6.3 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: White, Solid colour',
        'Price (MRP): Rs. 3,599.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      4,
      'Hi-top trainers',
      'https://i.imgur.com/JLxtdvX.png',
      'Rs. 3,599.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Retro-inspired hi-top trainers with a tongue and lacing at the front and a padded top edge. Jersey linings and insoles and soles that are patterned underneath. Height of soles 4.1 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Black/White, Block-coloured',
        'Price (MRP): Rs. 3,599.00 incl. of all taxes',
        'Country of production: Vietnam',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      5,
      'Slip-on cotton trainers',
      'https://i.imgur.com/esbQzJa.png',
      'Rs. 2,299.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Slip-on trainers in cotton canvas with a soft, padded top edge and elastic gores in the sides to make them comfy to get on and off. Piqué lining, canvas insoles and rubber soles that are patterned underneath. Height of soles 3.3 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Slip-on, Trainers',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 2,299.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      6,
      'Corduroy trainers',
      'https://i.imgur.com/vHPgl29.png',
      'Rs. 2,699.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers in cotton corduroy with lacing and a tongue at the front. Canvas linings and insoles and rubber soles that are patterned underneath. Height of soles 3.1 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Grey, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N',
      ],
    ),
    shoeCreate(
      7,
      'Trainers',
      'https://i.imgur.com/3eHM3UN.png',
      'Rs. 2,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers with a padded top edge and lacing at the front. Insoles in piqué and rubber soles that are patterned underneath. Height of soles 2.8 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N',
      ],
    ),
    shoeCreate(
      8,
      'Cotton canvas trainers',
      'https://i.imgur.com/S9G67Qi.png',
      'Rs. 1,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers in cotton canvas with a padded top edge, tongue and lacing at the front, and imitation leather heel caps. Linings and insoles in cotton canvas insoles and rubber soles that are patterned underneath. Height of soles 3 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Beige/White, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      9,
      'Cotton canvas trainers',
      'https://i.imgur.com/ydr5aTT.png',
      'Rs. 1,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers in cotton canvas with a padded top edge, tongue and lacing at the front, and imitation leather heel caps. Linings and insoles in cotton canvas insoles and rubber soles that are patterned underneath. Height of soles 3 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Dark blue/White, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      10,
      'Hi-top trainers',
      'https://i.imgur.com/WNu5AXX.png',
      'Rs. 2,699.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Hi-tops in sturdy cotton canvas with a padded shaft and a tongue and lacing at the front. Piqué linings and insoles and rubber soles that are patterned underneath. Height of soles 3.5 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      11,
      'Moccasin-seam shoes',
      'https://i.imgur.com/K9ePX3w.png',
      'Rs. 3,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Shoes with lacing and a moccasin seam at the front. Cotton canvas linings and insoles and rubber soles that are patterned underneath. Heel 1.5 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Derby shoes',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 3,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Smart shoe',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      12,
      'Chunky hi-tops',
      'https://i.imgur.com/tRvXyEh.png',
      'Rs. 3,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Hi-top trainers in cotton twill with lacing at the front and a loop at the back. Linings and insoles in piqué and chunky rubber soles. Height of soles 6.5 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: White, Solid colour',
        'Price (MRP): Rs. 3,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      13,
      'Trainers',
      'https://i.imgur.com/8vfJIsA.png',
      'Rs. 2,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers with a padded top edge and lacing at the front. Insoles in piqué and rubber soles that are patterned underneath. Height of soles 2.8 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: White, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
    shoeCreate(
      14,
      'Canvas trainers',
      'https://i.imgur.com/WbhVA7y.png',
      'Rs. 1,999.00',
      ['6.5', '7.5', '8', '9', '9.5', '10.5'],
      'Trainers in cotton canvas with lacing at the front and a loop at the back. Canvas linings and insoles and rubber soles that are patterned underneath. Height of soles 3.1 cm.',
      [
        'Heel Height: No heel',
        'Footwear Style: Trainers',
        'Description: Light purple, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Sneakers',
        'Net Quantity: 2 N (1 Pair)',
      ],
    ),
  ]);
}

async function createShirts() {
  console.log('Adding Shirts');
  await Promise.all([
    shirtCreate(
      0,
      'Regular Fit Rib-knit resort shirt',
      'https://i.imgur.com/jTiirnP.png',
      'Rs. 2,299.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Shirt in a rib-knit viscose and cotton blend. Regular fit with a resort collar, short sleeves and buttons down the front.',
      [
        'Size: Front: Length: 72.5 cm (Size L/L), Sleeve: Length: 24.0 cm (Size L/L)',
        'XS: Width: 98 cm, Length: 63 cm',
        'S: Width: 1.06 m, Length: 65 cm',
        'M: Width: 1.14 m, Length: 66 cm',
        'L: Width: 1.22 m, Length: 68 cm',
        'XL: Width: 1.30 m, Length: 69 cm',
        'XXL: Width: 1.38 m, Length: 70 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Regular fit',
        'Collar: Resort collar',
        'Description: Cream, Solid colour',
        'Price (MRP): Rs. 2,299.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Top',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      1,
      'Regular Fit Oxford shirt',
      'https://i.imgur.com/0TVnj0B.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XXL'],
      'Regular-fit shirt in Oxford cotton with a button-down collar, classic front, yoke at the back and an open chest pocket. Long sleeves with buttoned cuffs and a sleeve placket with a link button. Gently rounded hem.',
      [
        'Size: Sleeve: Length: 66.5 cm (Size L/L), Back: Length: 79.0 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 73 cm',
        'S: Width: 1.08 m, Length: 75 cm',
        'M: Width: 1.16 m, Length: 76 cm',
        'L: Width: 1.24 m, Length: 78 cm',
        'XXL: Width: 1.40 m, Length: 80 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Button-down collar',
        'Description: Light blue, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      2,
      'Regular Fit Oxford shirt',
      'https://i.imgur.com/xUpTUQb.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit shirt in Oxford cotton with a button-down collar, classic front, yoke at the back and an open chest pocket. Long sleeves with buttoned cuffs and a sleeve placket with a link button. Gently rounded hem.',
      [
        'Size: Sleeve: Length: 66.5 cm (Size L/L), Back: Length: 79.0 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 73 cm',
        'S: Width: 1.08 m, Length: 75 cm',
        'M: Width: 1.16 m, Length: 77 cm',
        'L: Width: 1.24 m, Length: 79 cm',
        'XL: Width: 1.32 m, Length: 80 cm',
        'XXL: Width: 1.40 m, Length: 81 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Button-down collar',
        'Description: Light greige, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      3,
      'Relaxed Fit Flannel shirt',
      'https://i.imgur.com/xCUaKFI.png',
      'Rs. 1,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Shirt in soft cotton flannel with a turn-down collar, buttons down the front and a yoke at the back. Relaxed fit with an open chest pocket and long sleeves with buttoned cuffs and a sleeve placket with a link button. Gently rounded hem.',
      [
        'Sleeve: Length: 65.0 cm (Size L/L), Back: Length: 81.5 cm (Size L/L)',
        'XS: Width: 1.07 m, Length: 73 cm',
        'S: Width: 1.15 m, Length: 75 cm',
        'M: Width: 1.23 m, Length: 77 cm',
        'L: Width: 1.31 m, Length: 79 cm',
        'XL: Width: 1.39 m, Length: 80 cm',
        'XXL: Width: 1.47 m, Length: 81 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Relaxed fit',
        'Collar: Turn-down collar',
        'Description: Red/Black, Checked',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: India',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      4,
      'Regular Fit Poplin shirt',
      'https://i.imgur.com/SWbv3tZ.png',
      'Rs. 1,999.00',
      ['XS', 'S', 'M', 'L', 'XL'],
      'Regular-fit shirt in cotton poplin with a turn-down collar, French front and a yoke at the back. Long sleeves with adjustable buttoning at the cuffs. Rounded hem.',
      [
        'Size: Shoulder: Width: 51.3 cm (Size L/L), Back: Length: 78.75 cm (Size L/L), Sleeve: Length: 67.0 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 70 cm',
        'S: Width: 1.08 m, Length: 72 cm',
        'M: Width: 1.16 m, Length: 74 cm',
        'L: Width: 1.24 m, Length: 76 cm',
        'XL: Width: 1.32 m, Length: 77 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      5,
      'Loose Fit Overshirt',
      'https://i.imgur.com/IMNDYaC.png',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Overshirt in woven fabric with a brushed finish. Loose fit with a collar, buttons down the front and a yoke at the back. Gently dropped shoulders, long sleeves with buttoned cuffs and open chest pockets. Gently rounded hem. Lined.',
      [
        'XS: Width: 1.04 m, Length: 71 cm',
        'S: Width: 1.12 m, Length: 73 cm',
        'M: Width: 1.20 m, Length: 75 cm',
        'L: Width: 1.28 m, Length: 77 cm',
        'XL: Width: 1.36 m, Length: 78 cm',
        'XXL: Width: 1.44 m, Length: 79 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Loose fit',
        'Collar: Turn-down collar',
        'Description: Dark grey, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      6,
      'Relaxed Fit Hooded overshirt',
      'https://i.imgur.com/WO0eQDd.png',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Relaxed-fit overshirt in cotton twill with a brushed finish, and a double-layered, drawstring hood in sweatshirt fabric. Yoke at the back, buttons down the front, dropped shoulders and long sleeves with buttoned cuffs. Flap chest pockets with a button, and discreet pockets in the side seams. Unlined.',
      [
        'Size: Sleeve: Length: 66.0 cm (Size L/L), Back: Length: 79.0 cm (Size L/L)',
        'XS: Width: 1.09 m, Length: 71 cm',
        'S: Width: 1.17 m, Length: 73 cm',
        'M: Width: 1.25 m, Length: 74 cm',
        'L: Width: 1.33 m, Length: 76 cm',
        'XL: Width: 1.41 m, Length: 77 cm',
        'XXL: Width: 1.49 m, Length: 79 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Relaxed fit',
        'Style: Overshirt',
        'Description: Beige/Blue, Checked',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      7,
      'Regular Fit Easy-iron shirt',
      'https://i.imgur.com/AQkRjnZ.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Shirt in woven fabric with an easy-iron finish. Turn-down collar, classic front, a yoke at the back and a rounded hem. Long sleeves with adjustable buttoning at the cuffs and a sleeve placket with a link button.',
      [
        'Size: Back: Length: 81.0 cm (Size L/L), Sleeve: Length: 67.25 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 71 cm',
        'S: Width: 1.08 m, Length: 73 cm',
        'M: Width: 1.16 m, Length: 75 cm',
        'L: Width: 1.24 m, Length: 77 cm',
        'XL: Width: 1.32 m, Length: 78 cm',
        'XXL: Width: 1.40 m, Length: 79 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Description: White, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      8,
      'Regular Fit Viscose shirt',
      'https://i.imgur.com/8dPqdoN.png',
      'Rs. 1,999.00',
      ['XS', 'S', 'M', 'L', 'XL'],
      'Regular-fit shirt in viscose with a turn-down collar, classic front and a yoke at the back. Long sleeves with buttoned cuffs and a sleeve placket with a link button. Rounded hem.',
      [
        'Size: Back: Length: 79.0 cm (Size L/L), Sleeve: Length: 67.0 cm (Size L/L), Shoulder: Width: 52.0 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 71 cm',
        'S: Width: 1.08 m, Length: 73 cm',
        'M: Width: 1.16 m, Length: 75 cm',
        'L: Width: 1.24 m, Length: 77 cm',
        'XL: Width: 1.32 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Description: Dark red, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      9,
      'Overshirt',
      'https://i.imgur.com/lnagAWp.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Overshirt in a soft weave with a collar, buttons down the front and a yoke at the back. Flap chest pockets with a button, and long sleeves with buttoned cuffs.',
      [
        'XS: Width: 1.02 m, Length: 70 cm',
        'S: Width: 1.10 m, Length: 72 cm',
        'M: Width: 1.18 m, Length: 74 cm',
        'L: Width: 1.26 m, Length: 76 cm',
        'XL: Width: 1.34 m, Length: 77 cm',
        'XXL: Width: 1.42 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Style: Overshirt, Shirt jacket',
        'Description: Dark red/White, Checked',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Myanmar',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      10,
      'Padded overshirt',
      'https://i.imgur.com/5Z6Gug6.png',
      'Rs. 3,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Relaxed-fit, lightly padded overshirt in soft cotton twill with a collar, press-studs down the front and a yoke at the back. Open chest pockets, long sleeves with a sleeve placket and buttoned cuffs, and a straight-cut hem. Quilted lining.',
      [
        'Size: Sleeve: Length: 66.25 cm (Size L/L), Back: Length: 78.0 cm (Size L/L)',
        'XS: Width: 1.09 m, Length: 71 cm',
        'S: Width: 1.17 m, Length: 72 cm',
        'M: Width: 1.25 m, Length: 74 cm',
        'L: Width: 1.33 m, Length: 75 cm',
        'XL: Width: 1.41 m, Length: 77 cm',
        'XXL: Width: 1.49 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Relaxed fit',
        'Collar: Turn-down collar',
        'Style: Overshirt',
        'Description: Light beige/Brown/Dark blue, Checked',
        'Price (MRP): Rs. 3,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      11,
      'Regular Fit Teddy-lined overshirt',
      'https://i.imgur.com/7k9zSvU.png',
      'Rs. 3,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Lightly padded overshirt in soft cotton twill with a collar, buttons down the front and a yoke at the back. Regular fit with flap chest pockets that have a concealed press-stud, long sleeves with a sleeve placket and buttoned cuffs, and a straight-cut hem. Teddy lining.',
      [
        'Size: Sleeve: Length: 65.75 cm (Size L/L), Back: Length: 78.0 cm (Size L/L)',
        'XS: Width: 1.09 m, Length: 71 cm',
        'S: Width: 1.17 m, Length: 72 cm',
        'M: Width: 1.25 m, Length: 74 cm',
        'L: Width: 1.33 m, Length: 75 cm',
        'XL: Width: 1.41 m, Length: 77 cm',
        'XXL: Width: 1.49 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Style: Overshirt',
        'Description: Cream/Black, Checked',
        'Price (MRP): Rs. 3,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      12,
      'Regular Fit Corduroy shirt',
      'https://i.imgur.com/MlwZHZB.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit shirt in soft cotton corduroy with a turn-down collar, classic front, open chest pocket and yoke at the back. Long sleeves with buttoned cuffs and a sleeve placket with a link button. Rounded hem.',
      [
        'Size: Sleeve: Length: 65.5 cm (Size L/L), Back: Length: 78.5 cm (Size L/L), Shoulder: Width: 50.5 cm (Size L/L)',
        'XS: Width: 100 cm, Length: 70 cm',
        'S: Width: 1.08 m, Length: 72 cm',
        'M: Width: 1.16 m, Length: 74 cm',
        'L: Width: 1.24 m, Length: 76 cm',
        'XL: Width: 1.32 m, Length: 77 cm',
        'XXL: Width: 1.40 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Description: Burgundy, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      13,
      'Overshirt',
      'https://i.imgur.com/sgR4fO2.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Overshirt in a soft weave with a collar, buttons down the front and a yoke at the back. Flap chest pockets with a button, and long sleeves with buttoned cuffs.',
      [
        'XS: Width: 1.02 m, Length: 70 cm',
        'S: Width: 1.10 m, Length: 72 cm',
        'M: Width: 1.18 m, Length: 74 cm',
        'L: Width: 1.26 m, Length: 76 cm',
        'XL: Width: 1.34 m, Length: 77 cm',
        'XXL: Width: 1.42 m, Length: 78 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Style: Overshirt, Shirt jacket',
        'Description: Beige/Black/Blue, Checked',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
    shirtCreate(
      14,
      'Regular Fit Felted overshirt',
      'https://i.imgur.com/4eMveQ4.jpg',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Overshirt in felted fabric with a collar, zip down the front and a yoke at the back. Flap chest pockets, long sleeves with a slit and button at the cuffs, and a straight-cut hem. Regular fit for comfortable wear and a classic silhouette.',
      [
        'Size: Back: Length: 75.5 cm (Size L/L), Sleeve: Length: 67.0 cm (Size L/L)',
        'XS: Width: 1.06 m, Length: 68 cm',
        'S: Width: 1.14 m, Length: 70 cm',
        'M: Width: 1.22 m, Length: 71 cm',
        'L: Width: 1.30 m, Length: 73 cm',
        'XL: Width: 1.38 m, Length: 74 cm',
        'XXL: Width: 1.46 m, Length: 76 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Style: Overshirt',
        'Description: Dark blue/White, Checked',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Shirt',
        'Net Quantity: 1 N',
      ],
    ),
  ]);
}

async function createJeans() {
  console.log('Adding Jeans');
  await Promise.all([
    jeanCreate(
      0,
      'Straight Regular Jeans',
      'https://i.imgur.com/EkbAuTD.png',
      'Rs. 1,799.00',
      [
        '28/28',
        '29/28',
        '29/30',
        '30/28',
        '30/30',
        '30/32',
        '31/28',
        '31/30',
        '32/28',
        '32/30',
        '32/32',
        '33/30',
        '34/30',
        '34/32',
        '36/30',
        '38/30',
      ],
      '5-pocket jeans in cotton denim with a slight stretch for good comfort. Straight leg and a regular fit from the waist to the hem with a comfortable, looser feel around the whole leg. Regular waist and a zip fly. This is denim that lasts.',
      [
        '29/30: Width: 79 cm, Length: 74 cm',
        '30/30: Width: 81 cm, Length: 74 cm',
        '30/32: Width: 81 cm, Length: 78 cm',
        '31/30: Width: 84 cm, Length: 75 cm',
        '32/30: Width: 86 cm, Length: 75 cm',
        '32/32: Width: 86 cm, Length: 79 cm',
        '33/30: Width: 89 cm, Length: 76 cm',
        '34/30: Width: 91 cm, Length: 76 cm',
        '34/32: Width: 91 cm, Length: 80 cm',
        '36/30: Width: 96 cm, Length: 77 cm',
        '38/30: Width: 1.01 m, Length: 77 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Regular fit',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 1,799.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      1,
      'Skinny Jeans',
      'https://i.imgur.com/IA3FBAe.png',
      'Rs. 1,799.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '30/32',
        '31/30',
        '31/32',
        '32/30',
        '32/32',
        '33/30',
        '33/32',
        '34/30',
        '36/30',
        '38/30',
        '40/30',
      ],
      '5-pocket jeans in cotton denim with a premium stretch for excellent comfort. Skinny fit from the waist to the hem, a regular waist and a zip fly. Designed for everyday wear.',
      [
        '28/30: Width: 72 cm, Length: 73 cm',
        '29/30: Width: 74 cm, Length: 74 cm',
        '30/30: Width: 77 cm, Length: 74 cm',
        '30/32: Width: 77 cm, Length: 78 cm',
        '31/30: Width: 79 cm, Length: 75 cm',
        '31/32: Width: 79 cm, Length: 79 cm',
        '32/30: Width: 82 cm, Length: 75 cm',
        '32/32: Width: 82 cm, Length: 79 cm',
        '33/30: Width: 84 cm, Length: 76 cm',
        '33/32: Width: 84 cm, Length: 80 cm',
        '34/30: Width: 86 cm, Length: 76 cm',
        '36/30: Width: 91 cm, Length: 77 cm',
        '38/30: Width: 95 cm, Length: 77 cm',
        '40/30: Width: 100 cm, Length: 77 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Skinny fit',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 1,799.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      2,
      'Loose Jeans',
      'https://i.imgur.com/ZTAy67V.png',
      'Rs. 1,999.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '31/30',
        '32/30',
        '33/30',
        '34/30',
        '36/30',
        '38/30',
        '40/30',
      ],
      '5-pocket jeans in rigid cotton denim with a rounded leg and a loose fit from the seat to the hem with a dropped crotch and extra room around the whole leg. Regular waist and a zip fly. These will be your new favourites.',
      [
        'Size: Waist: Circumference: 91.0 cm (Size 33/32)',
        '28/30: Width: 79 cm, Length: 70 cm',
        '29/30: Width: 81 cm, Length: 71 cm',
        '30/30: Width: 84 cm, Length: 71 cm',
        '31/30: Width: 86 cm, Length: 72 cm',
        '32/30: Width: 89 cm, Length: 72 cm',
        '33/30: Width: 91 cm, Length: 73 cm',
        '34/30: Width: 94 cm, Length: 73 cm',
        '36/30: Width: 98 cm, Length: 74 cm',
        '38/30: Width: 1.03 m, Length: 74 cm',
        '40/30: Width: 1.08 m, Length: 74 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Loose fit',
        'Description: Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      3,
      'Slim Jeans',
      'https://i.imgur.com/bH8lZsA.png',
      'Rs. 1,799.00',
      [
        '28/28',
        '28/30',
        '28/32',
        '29/28',
        '29/30',
        '29/32',
        '30/28',
        '30/30',
        '30/32',
        '31/28',
        '31/30',
        '31/32',
        '32/28',
        '32/30',
        '32/32',
        '32/34',
        '33/30',
        '33/32',
        '33/34',
        '34/30',
        '34/32',
        '34/34',
        '36/30',
        '36/32',
        '36/34',
        '38/30',
        '38/32',
        '40/30',
        '40/32',
        '42/32',
        '44/32',
      ],
      '5-pocket jeans in cotton denim with a slight stretch for good comfort. Straight leg and a slim fit from the waist through the thigh to the hem. Regular waist and a zip fly. Easily styled for sleek or sporty.',
      [
        '28/28: Width: 77 cm, Length: 71 cm',
        '28/30: Width: 77 cm, Length: 75 cm',
        '28/32: Width: 77 cm, Length: 79 cm',
        '29/28: Width: 80 cm, Length: 72 cm',
        '29/30: Width: 80 cm, Length: 76 cm',
        '29/32: Width: 80 cm, Length: 80 cm',
        '30/28: Width: 82 cm, Length: 72 cm',
        '30/30: Width: 82 cm, Length: 76 cm',
        '30/32: Width: 82 cm, Length: 80 cm',
        '31/28: Width: 85 cm, Length: 72 cm',
        '31/30: Width: 85 cm, Length: 76 cm',
        '31/32: Width: 85 cm, Length: 80 cm',
        '32/28: Width: 87 cm, Length: 72 cm',
        '32/30: Width: 87 cm, Length: 76 cm',
        '32/32: Width: 86 cm, Length: 79 cm',
        '32/34: Width: 87 cm, Length: 84 cm',
        '33/30: Width: 90 cm, Length: 77 cm',
        '33/32: Width: 90 cm, Length: 81 cm',
        '33/34: Width: 90 cm, Length: 85 cm',
        '34/30: Width: 92 cm, Length: 77 cm',
        '34/32: Width: 91 cm, Length: 80 cm',
        '34/34: Width: 92 cm, Length: 85 cm',
        '36/30: Width: 97 cm, Length: 78 cm',
        '36/32: Width: 97 cm, Length: 82 cm',
        '36/34: Width: 97 cm, Length: 86 cm',
        '38/30: Width: 1.02 m, Length: 78 cm',
        '38/32: Width: 1.02 m, Length: 82 cm',
        '40/30: Width: 1.07 m, Length: 79 cm',
        '40/32: Width: 1.07 m, Length: 83 cm',
        '42/32: Width: 1.07 m, Length: 83 cm',
        '44/32: Width: 1.17 m, Length: 83 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Slim fit',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 1,799.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      4,
      'Relaxed Jeans',
      'https://i.imgur.com/ahIKJsM.png',
      'Rs. 2,699.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '31/30',
        '32/30',
        '33/30',
        '34/30',
        '36/30',
        '38/30',
        '40/30',
      ],
      '5-pocket jeans in rigid cotton denim with a straight leg and a relaxed fit from the seat to the hem with extra room from the thigh down. Regular waist and a zip fly. Designed for everyday wear.',
      [
        'Size: Inside leg: Length: 89.5 cm (Size 33), Waist: Circumference: 90.5 cm (Size 33)',
        '28/30: Width: 78 cm, Length: 75 cm',
        '29/30: Width: 81 cm, Length: 76 cm',
        '30/30: Width: 83 cm, Length: 76 cm',
        '31/30: Width: 86 cm, Length: 76 cm',
        '32/30: Width: 88 cm, Length: 76 cm',
        '33/30: Width: 91 cm, Length: 77 cm',
        '34/30: Width: 93 cm, Length: 77 cm',
        '36/30: Width: 98 cm, Length: 78 cm',
        '38/30: Width: 1.03 m, Length: 78 cm',
        '40/30: Width: 1.75 m, Length: 79 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Relaxed fit',
        'Style: Straight leg',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      5,
      'Loose Jeans',
      'https://i.imgur.com/Uc8Y5vF.png',
      'Rs. 2,299.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '30/32',
        '31/30',
        '31/32',
        '32/30',
        '32/32',
        '33/30',
        '33/32',
        '34/30',
        '34/32',
        '36/30',
        '36/32',
        '38/30',
        '40/30',
      ],
      '5-pocket jeans in rigid cotton denim with a rounded leg and a loose fit from the seat to the hem with a dropped crotch and extra room around the whole leg. Regular waist and a zip fly. All you need to conquer the full denim look.',
      [
        '28/30: Width: 79 cm, Length: 70 cm',
        '29/30: Width: 81 cm, Length: 71 cm',
        '30/30: Width: 84 cm, Length: 71 cm',
        '30/32: Width: 84 cm, Length: 75 cm',
        '31/30: Width: 86 cm, Length: 72 cm',
        '31/32: Width: 86 cm, Length: 76 cm',
        '32/30: Width: 89 cm, Length: 72 cm',
        '32/32: Width: 89 cm, Length: 76 cm',
        '33/30: Width: 91 cm, Length: 73 cm',
        '33/32: Width: 91 cm, Length: 77 cm',
        '34/30: Width: 94 cm, Length: 73 cm',
        '34/32: Width: 94 cm, Length: 77 cm',
        '36/30: Width: 98 cm, Length: 74 cm',
        '36/32: Width: 98 cm, Length: 78 cm',
        '38/30: Width: 1.03 m, Length: 74 cm',
        '40/30: Width: 1.08 m, Length: 74 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Loose fit',
        'Description: Light denim blue, Solid colour',
        'Price (MRP): Rs. 2,299.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    jeanCreate(
      6,
      'Straight Regular Jeans',
      'https://i.imgur.com/3urxWJg.jpg',
      'Rs. 2,299.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '30/32',
        '31/30',
        '31/32',
        '32/30',
        '32/32',
        '33/30',
        '33/32',
        '34/30',
        '34/32',
        '36/30',
        '38/30',
        '40/30',
      ],
      '5-pocket jeans in cotton denim with a slight stretch for good comfort. Straight leg and a regular fit from the waist to the hem with a comfortable, looser feel around the whole leg. Regular waist and a zip fly. This is denim that lasts.',
      [
        '28/30: Width: 76 cm, Length: 73 cm',
        '29/30: Width: 79 cm, Length: 74 cm',
        '30/30: Width: 81 cm, Length: 74 cm',
        '30/32: Width: 81 cm, Length: 78 cm',
        '31/30: Width: 84 cm, Length: 75 cm',
        '31/32: Width: 84 cm, Length: 79 cm',
        '32/30: Width: 86 cm, Length: 75 cm',
        '32/32: Width: 86 cm, Length: 79 cm',
        '33/30: Width: 89 cm, Length: 76 cm',
        '33/32: Width: 89 cm, Length: 80 cm',
        '34/30: Width: 91 cm, Length: 76 cm',
        '34/32: Width: 91 cm, Length: 80 cm',
        '36/30: Width: 96 cm, Length: 77 cm',
        '38/30: Width: 1.01 m, Length: 77 cm',
        '40/30: Width: 1.06 m, Length: 77 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Regular fit',
        'Style: Straight leg',
        'Description: Denim blue, Solid colour',
        'Price (MRP): Rs. 2,299.00 incl. of all taxes',
        'Country of production: India',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
  ]);
}

async function createTrousers() {
  console.log('Adding Trousers');
  await Promise.all([
    trouserCreate(
      0,
      'Regular Fit Cargo trousers',
      'https://i.imgur.com/83sDWgv.png',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit cargo trousers in cotton twill with sewn-in pleats at the knees. Covered elastication at the back of the waist, zip fly and a press-stud. Welt side pockets with a press-stud, bellows leg pockets with press-studs and welt back pockets.',
      [
        'Size: Inside leg: Length: 76.5 cm (Size L/L)',
        'XS: Width: 71 cm, Length: 70 cm',
        'S: Width: 78 cm, Length: 71 cm',
        'M: Width: 85 cm, Length: 72 cm',
        'L: Width: 92 cm, Length: 73 cm',
        'XL: Width: 99 cm, Length: 73 cm',
        'XXL: Width: 1.07 m, Length: 74 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Regular fit',
        'Style: Cargo, Straight leg',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: Myanmar',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      1,
      'Regular Fit Corduroy trousers',
      'https://i.imgur.com/Rpbtu3c.png',
      'Rs. 2,999.00',
      ['28', '29', '30', '31', '32', '33', '34', '36'],
      'Trousers in soft cotton corduroy with pleats at the top of the front for added width. Regular fit with a zip fly and button, diagonal side pockets and jetted back pockets with a button.',
      [
        'Size: Inside leg: Length: 76.0 cm (Size 33L)',
        '28: Width: 79 cm, Length: 70 cm',
        '29: Width: 82 cm, Length: 71 cm',
        '30: Width: 84 cm, Length: 71 cm',
        '31: Width: 87 cm, Length: 71 cm',
        '32: Width: 89 cm, Length: 71 cm',
        '33: Width: 92 cm, Length: 72 cm',
        '34: Width: 94 cm, Length: 72 cm',
        '36: Width: 99 cm, Length: 73 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Regular fit',
        'Description: Brown, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      2,
      'Loose Fit Corduroy pull-on trousers',
      'https://i.imgur.com/PvEnOrw.png',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Loose-fit trousers in soft cotton corduroy featuring a fake fly and covered elastication and an elasticated drawstring with cord stoppers at the waist. Diagonal side pockets with a flap and concealed press-stud, a patch back pocket, knee pleats for added volume and an elasticated drawstring with a cord stopper at the hems.',
      [
        'Size: Inside leg: Length: 76.0 cm (Size L/L)',
        'XS: Width: 71 cm, Length: 69 cm',
        'S: Width: 78 cm, Length: 70 cm',
        'M: Width: 85 cm, Length: 72 cm',
        'L: Width: 92 cm, Length: 72 cm',
        'XL: Width: 99 cm, Length: 73 cm',
        'XXL: Width: 1.06 m, Length: 73 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Loose fit',
        'Style: Joggers, Pull-on trousers',
        'Description: Cream, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      3,
      'Relaxed Fit Nylon cargo trousers',
      'https://i.imgur.com/VKrmQ46.png',
      'Rs. 3,599.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Cargo trousers in nylon with an elasticated, drawstring waist. Relaxed fit with a fake fly, zipped side pockets, flap back pockets with concealed press-studs and drawstring leg pockets with a flap with concealed press-studs. Elasticated drawstring at the hems.',
      [
        'Size: Inside leg: Length: 75.7 cm (Size L/L)',
        'XS: Width: 73 cm, Length: 69 cm',
        'S: Width: 80 cm, Length: 70 cm',
        'M: Width: 87 cm, Length: 71 cm',
        'L: Width: 94 cm, Length: 72 cm',
        'XL: Width: 1.01 m, Length: 72 cm',
        'XXL: Width: 1.08 m, Length: 73 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Relaxed fit',
        'Style: Cargo',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 3,599.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      4,
      'Regular Fit Twill joggers',
      'https://i.imgur.com/kMrR0wq.png',
      'Rs. 2,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Ankle-length joggers in twill. Regular fit with covered elastication at the waist, a zip fly and button, diagonal side pockets, welt back pockets with a button, and straight legs.',
      [
        'XS: Width: 70 cm, Length: 65 cm',
        'S: Width: 77 cm, Length: 66 cm',
        'M: Width: 84 cm, Length: 67 cm',
        'L: Width: 91 cm, Length: 68 cm',
        'XL: Width: 99 cm, Length: 69 cm',
        'XXL: Width: 1.06 m, Length: 69 cm',
        'Length: Ankle length',
        'Waist Rise: Regular waist',
        'Fit: Regular fit',
        'Style: Joggers, Straight leg',
        'Description: Greige, Solid colour',
        'Price (MRP): Rs. 2,999.00 incl. of all taxes',
        'Country of production: Myanmar',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      5,
      'Slim Fit Corduroy trousers',
      'https://i.imgur.com/xm99EDB.png',
      'Rs. 2,699.00',
      ['28', '29', '30', '31', '32', '33', '34', '36'],
      '5-pocket trousers in soft cotton corduroy. Slim fit with a zip fly and button.',
      [
        '28: Width: 79 cm, Length: 73 cm',
        '29: Width: 81 cm, Length: 74 cm',
        '30: Width: 84 cm, Length: 74 cm',
        '31: Width: 86 cm, Length: 75 cm',
        '32: Width: 89 cm, Length: 75 cm',
        '33: Width: 91 cm, Length: 76 cm',
        '34: Width: 94 cm, Length: 76 cm',
        '36: Width: 98 cm, Length: 77 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Slim fit',
        'Description: Beige, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      6,
      'Relaxed Fit Cargo trousers',
      'https://i.imgur.com/aPUxWI1.png',
      'Rs. 3,599.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Relaxed-fit trousers in a cotton weave with a regular waist with covered elastication and a drawstring. Diagonal side pockets, back and leg pockets with a flap that has a hook and loop fastening, and a concealed leg pocket with a zip. Seams at the knees and an elasticated drawstring at the hems.',
      [
        'Size: Inside leg: Length: 77.0 cm (Size L/L)',
        'XS: Width: 72 cm, Length: 70 cm',
        'S: Width: 79 cm, Length: 71 cm',
        'M: Width: 86 cm, Length: 72 cm',
        'L: Width: 93 cm, Length: 73 cm',
        'XL: Width: 100 cm, Length: 74 cm',
        'XXL: Width: 1.08 m, Length: 74 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Relaxed fit',
        'Style: Cargo',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 3,599.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      7,
      'Slim Fit Cotton twill trousers',
      'https://i.imgur.com/DvfmJJv.png',
      'Rs. 1,499.00',
      [
        '28/28',
        '28/30',
        '29/28',
        '29/30',
        '30/28',
        '30/30',
        '30/32',
        '31/28',
        '31/30',
        '31/32',
        '32/28',
        '32/30',
        '32/32',
        '33/30',
        '33/32',
        '34/30',
        '36/30',
        '38/30',
      ],
      '5-pocket slim-fit trousers in cotton twill with a zip fly and button.',
      [
        'Size: Inside leg: Length: 79.5 cm (Size 33/32)',
        '28/30: Width: 79 cm, Length: 73 cm',
        '29/30: Width: 81 cm, Length: 74 cm',
        '30/30: Width: 84 cm, Length: 74 cm',
        '30/32: Width: 84 cm, Length: 78 cm',
        '31/30: Width: 86 cm, Length: 75 cm',
        '31/32: Width: 86 cm, Length: 79 cm',
        '32/30: Width: 89 cm, Length: 75 cm',
        '32/32: Width: 89 cm, Length: 79 cm',
        '33/30: Width: 91 cm, Length: 76 cm',
        '33/32: Width: 91 cm, Length: 80 cm',
        '34/30: Width: 94 cm, Length: 76 cm',
        '36/30: Width: 98 cm, Length: 77 cm',
        '38/30: Width: 1.03 m, Length: 77 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Slim fit',
        'Description: Khaki green, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
    trouserCreate(
      8,
      'Slim Fit Cotton chinos',
      'https://i.imgur.com/E8CxO6u.png',
      'Rs. 1,999.00',
      [
        '28/30',
        '29/30',
        '30/30',
        '30/32',
        '31/30',
        '31/32',
        '32/30',
        '32/32',
        '33/30',
        '33/32',
        '34/30',
        '36/30',
        '38/30',
        '40/30',
      ],
      'Slim-fit chinos in stretch cotton twill with a zip fly, side pockets and welt back pockets with a button.',
      [
        'Size: Inside leg: Length: 78.0 cm (Size 33/32), Waist: Circumference: 90.0 cm (Size 33/32)',
        '28/30: Width: 78 cm, Length: 72 cm',
        '29/30: Width: 80 cm, Length: 73 cm',
        '30/30: Width: 83 cm, Length: 73 cm',
        '30/32: Width: 83 cm, Length: 77 cm',
        '31/30: Width: 85 cm, Length: 73 cm',
        '31/32: Width: 85 cm, Length: 77 cm',
        '32/30: Width: 88 cm, Length: 73 cm',
        '32/32: Width: 88 cm, Length: 77 cm',
        '33/30: Width: 90 cm, Length: 74 cm',
        '33/32: Width: 90 cm, Length: 78 cm',
        '34/30: Width: 93 cm, Length: 74 cm',
        '36/30: Width: 98 cm, Length: 75 cm',
        '38/30: Width: 1.03 m, Length: 75 cm',
        '40/30: Width: 1.08 m, Length: 76 cm',
        'Length: Long',
        'Waist Rise: Regular waist',
        'Fit: Slim fit',
        'Style: Chinos',
        'Description: Grey, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: Myanmar',
        'Common generic name: Trousers',
        'Net Quantity: 1 N',
      ],
    ),
  ]);
}

async function createTShirts() {
  console.log('Adding TShirts');
  await Promise.all([
    tshirtCreate(
      0,
      'Regular Fit Polo shirt',
      'https://i.imgur.com/sLR4inR.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Polo shirt in soft, fine-knit cotton. Regular fit with a collar, button placket and long sleeves. Fine ribbing at the cuffs and hem.',
      [
        'XS: Width: 96 cm, Length: 66 cm',
        'S: Width: 1.04 m, Length: 68 cm',
        'M: Width: 1.12 m, Length: 69 cm',
        'L: Width: 1.20 m, Length: 71 cm',
        'XL: Width: 1.28 m, Length: 72 cm',
        'XXL: Width: 1.36 m, Length: 73 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Style: Polo shirt',
        'Description: Dark blue, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      1,
      'Regular Fit Jersey top',
      'https://i.imgur.com/rbVURK0.png',
      'Rs. 799.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Top in lightweight cotton jersey with a round, rib-trimmed neckline, long sleeves and a straight-cut hem. Regular fit for comfortable wear and a classic silhouette.',
      [
        'XS: Width: 94 cm, Length: 68 cm',
        'S: Width: 1.02 m, Length: 69 cm',
        'M: Width: 1.10 m, Length: 71 cm',
        'L: Width: 1.18 m, Length: 72 cm',
        'XL: Width: 1.26 m, Length: 73 cm',
        'XXL: Width: 1.34 m, Length: 75 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Neckline: Round neck',
        'Description: Black, Solid colour',
        'Concept: BASICS',
        'Price (MRP): Rs. 799.00 incl. of all taxes',
        'Country of production: India',
        'Common generic name: T-shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      2,
      'Regular Fit Rib-knit T-shirt',
      'https://i.imgur.com/0uHZK5l.png',
      'Rs. 1,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit T-shirt in a soft, rib-knit cotton blend with a round neckline and a straight hem.',
      [
        'XS: Width: 92 cm, Length: 62 cm',
        'S: Width: 100 cm, Length: 64 cm',
        'M: Width: 1.08 m, Length: 65 cm',
        'L: Width: 1.16 m, Length: 67 cm',
        'XL: Width: 1.24 m, Length: 68 cm',
        'XXL: Width: 1.32 m, Length: 69 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Regular fit',
        'Neckline: Round neck',
        'Description: Cream, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: T-shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      3,
      'Regular Fit T-shirt',
      'https://i.imgur.com/WoUTm4L.png',
      'Rs. 399.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'T-shirt in lightweight cotton jersey with a round, rib-trimmed neckline and a straight-cut hem. Regular fit for comfortable wear and a classic silhouette.',
      [
        'XS: Width: 94 cm, Length: 68 cm',
        'S: Width: 1.02 m, Length: 69 cm',
        'M: Width: 1.10 m, Length: 71 cm',
        'L: Width: 1.18 m, Length: 72 cm',
        'XL: Width: 1.26 m, Length: 74 cm',
        'XXL: Width: 1.34 m, Length: 75 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Regular fit',
        'Neckline: Round neck',
        'Description: Burgundy, Solid colour',
        'Price (MRP): Rs. 399.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: T-shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      4,
      'Relaxed Fit Crochet-look polo shirt',
      'https://i.imgur.com/JGfsVq9.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Relaxed-fit polo shirt in hole-knit cotton with a crocheted look. Collar, V-shaped opening at the top, short sleeves and ribbing around the cuffs and hem.',
      [
        'XS: Width: 1.04 m, Length: 62 cm',
        'S: Width: 1.12 m, Length: 64 cm',
        'M: Width: 1.20 m, Length: 65 cm',
        'L: Width: 1.28 m, Length: 67 cm',
        'XL: Width: 1.36 m, Length: 68 cm',
        'XXL: Width: 1.42 m, Length: 69 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Relaxed fit',
        'Collar: Johnny collar',
        'Style: Polo shirt',
        'Neckline: V-neck',
        'Description: Cream, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      5,
      'Regular Fit Fine-knit polo shirt',
      'https://i.imgur.com/xy3970z.png',
      'Rs. 2,299.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit polo shirt in a soft, fine-knit cotton blend with a collar, small V-shaped opening at the top and short sleeves. Fine ribbing at the cuffs and hem.',
      [
        'XS: Width: 96 cm, Length: 64 cm',
        'S: Width: 1.04 m, Length: 66 cm',
        'M: Width: 1.12 m, Length: 67 cm',
        'L: Width: 1.20 m, Length: 69 cm',
        'XL: Width: 1.28 m, Length: 70 cm',
        'XXL: Width: 1.36 m, Length: 71 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Regular fit',
        'Collar: Johnny collar',
        'Style: Polo shirt',
        'Description: Dark blue/White, Striped',
        'Price (MRP): Rs. 2,299.00 incl. of all taxes',
        'Country of production: China',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      6,
      'Regular Fit Polo shirt',
      'https://i.imgur.com/GsxpSKR.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit polo shirt in sweatshirt fabric with a soft brushed inside. Collar, a button placket, dropped shoulders and long sleeves. Ribbing at the cuffs and hem.',
      [
        'XS: Width: 98 cm, Length: 68 cm',
        'S: Width: 1.06 m, Length: 69 cm',
        'M: Width: 1.14 m, Length: 71 cm',
        'L: Width: 1.22 m, Length: 72 cm',
        'XL: Width: 1.30 m, Length: 73 cm',
        'XXL: Width: 1.38 m, Length: 75 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Style: Polo shirt',
        'Description: Beige, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Cambodia',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    tshirtCreate(
      7,
      'Loose Fit T-shirt',
      'https://i.imgur.com/ovwJrkX.png',
      'Rs. 799.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Loose-fit T-shirt in cotton jersey with a round, rib-trimmed neckline.',
      [
        'XS: Width: 100 cm, Length: 68 cm',
        'S: Width: 1.08 m, Length: 69 cm',
        'M: Width: 1.16 m, Length: 70 cm',
        'L: Width: 1.24 m, Length: 72 cm',
        'XL: Width: 1.32 m, Length: 73 cm',
        'XXL: Width: 1.40 m, Length: 74 cm',
        'Length: Regular length',
        'Sleeve Length: Short sleeve',
        'Fit: Loose fit',
        'Neckline: Round neck',
        'Description: Dark green/Light blue/Pink/Orange/Dark turquoise/White, Leave no space behind',
        'Price (MRP): Rs. 799.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: T-shirt',
        'Net Quantity: 1 N',
      ],
    ),
  ]);
}

async function createSweatshirts() {
  console.log('Adding Sweatshirts');
  await Promise.all([
    sweatshirtCreate(
      0,
      'Loose Fit Sweatshirt',
      'https://i.imgur.com/Q1Ku3D3.png',
      'Rs. 799.00',
      ['XS', 'S', 'M', 'L', 'XL'],
      'Top in lightweight sweatshirt fabric made from a cotton blend with a soft brushed inside. Round, rib-trimmed neckline, dropped shoulders, long sleeves and wide ribbing at the cuffs and hem. Loose fit for a generous but not oversized silhouette.',
      [
        'XS: Width: 1.04 m, Length: 66 cm',
        'S: Width: 1.12 m, Length: 67 cm',
        'M: Width: 1.20 m, Length: 69 cm',
        'L: Width: 1.28 m, Length: 70 cm',
        'XL: Width: 1.36 m, Length: 71 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Loose fit',
        'Style: Sweatshirt',
        'Neckline: Round neck',
        'Description: Black, Solid colour',
        'Price (MRP): Rs. 799.00 incl. of all taxes',
        'Country of production: Indonesia',
        'Common generic name: Jumper/Sweater',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      1,
      'Regular Fit Polo shirt',
      'https://i.imgur.com/Ocv56uN.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit polo shirt in sweatshirt fabric with a soft brushed inside. Collar, a button placket, dropped shoulders and long sleeves. Ribbing at the cuffs and hem.',
      [
        'XS: Width: 98 cm, Length: 68 cm',
        'S: Width: 1.06 m, Length: 69 cm',
        'M: Width: 1.14 m, Length: 71 cm',
        'L: Width: 1.22 m, Length: 72 cm',
        'XL: Width: 1.30 m, Length: 73 cm',
        'XXL: Width: 1.38 m, Length: 75 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Style: Polo shirt',
        'Description: Navy blue, Solid colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Cambodia',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      2,
      'Regular Fit Zip-top sweatshirt',
      'https://i.imgur.com/DsP1sEZ.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Top in sweatshirt fabric made from a cotton blend with a soft brushed inside. Regular fit with a stand-up collar, zip at the top, long sleeves and wide ribbing at the cuffs and hem.',
      [
        'XS: Width: 98 cm, Length: 67 cm',
        'S: Width: 1.06 m, Length: 68 cm',
        'M: Width: 1.14 m, Length: 70 cm',
        'L: Width: 1.22 m, Length: 71 cm',
        'XL: Width: 1.38 m, Length: 73 cm',
        'XXL: Width: 1.46 m, Length: 74 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Stand-up collar',
        'Style: Sweatshirt',
        'Description: Light grey marl',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Cambodia',
        'Common generic name: Jumper/Sweater',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      3,
      'Regular Fit Cotton rugby shirt',
      'https://i.imgur.com/rrd712u.png',
      'Rs. 1,499.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Regular-fit rugby shirt in soft cotton jersey with a collar, concealed button placket and long sleeves with ribbed cuffs. Small slit at each side of the hem.',
      [
        'XS: Width: 100 cm, Length: 70 cm',
        'S: Width: 1.08 m, Length: 71 cm',
        'M: Width: 1.16 m, Length: 73 cm',
        'L: Width: 1.24 m, Length: 74 cm',
        'XL: Width: 1.32 m, Length: 75 cm',
        'XXL: Width: 1.40 m, Length: 76 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Regular fit',
        'Collar: Turn-down collar',
        'Style: Rugby shirt, Slit',
        'Description: Dark red, Sold colour',
        'Price (MRP): Rs. 1,499.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Polo shirt',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      4,
      'Oversized Fit Printed sweatshirt',
      'https://i.imgur.com/Js2CHNk.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Oversized top in printed sweatshirt fabric with a soft brushed inside. Round, rib-trimmed neckline, dropped shoulders and long sleeves. Ribbing at the cuffs and hem.',
      [
        'XS: Width: 1.12 m, Length: 67 cm',
        'S: Width: 1.20 m, Length: 68 cm',
        'M: Width: 1.28 m, Length: 69 cm',
        'L: Width: 1.36 m, Length: 70 cm',
        'XL: Width: 1.44 m, Length: 71 cm',
        'XXL: Width: 1.50 m, Length: 72 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Oversized',
        'Style: Sweatshirt',
        'Neckline: Round neck',
        'Description: Yellow/Black, Without boundaries',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Myanmar',
        'Common generic name: Jumper/Sweater',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      5,
      'Oversized Fit Half-zip sweatshirt',
      'https://i.imgur.com/thVCYgO.png',
      'Rs. 1,999.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Top in jersey made from a cotton blend with a soft, brushed inside. Oversized fit with a stand-up collar, zip at the top, dropped shoulders and long sleeves. Ribbing around the cuffs and hem.',
      [
        'XS: Width: 1.14 m, Length: 64 cm',
        'S: Width: 1.22 m, Length: 66 cm',
        'M: Width: 1.30 m, Length: 67 cm',
        'L: Width: 1.38 m, Length: 69 cm',
        'XL: Width: 1.46 m, Length: 70 cm',
        'XXL: Width: 1.52 m, Length: 71 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Oversized',
        'Collar: Stand-up collar',
        'Style: Sweatshirt',
        'Description: Light beige, Solid colour',
        'Price (MRP): Rs. 1,999.00 incl. of all taxes',
        'Country of production: Bangladesh',
        'Common generic name: Jumper/Sweater',
        'Net Quantity: 1 N',
      ],
    ),
    sweatshirtCreate(
      6,
      'Relaxed Fit Zip-through jacket',
      'https://i.imgur.com/CCz9Hh6.png',
      'Rs. 2,699.00',
      ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      'Jacket in cotton sweatshirt fabric with a soft brushed inside. Relaxed fit with a stand-up collar, zip down the front, dropped shoulders and long sleeves. Kangaroo pockets and covered elastication at the cuffs and hem.',
      [
        'XS: Width: 1.04 m, Length: 65 cm',
        'S: Width: 1.12 m, Length: 67 cm',
        'M: Width: 1.20 m, Length: 68 cm',
        'L: Width: 1.28 m, Length: 70 cm',
        'XL: Width: 1.36 m, Length: 71 cm',
        'XXL: Width: 1.44 m, Length: 72 cm',
        'Length: Regular length',
        'Sleeve Length: Long sleeve',
        'Fit: Relaxed fit',
        'Collar: Stand-up collar',
        'Style: Track jacket',
        'Description: Light greige, Solid colour',
        'Price (MRP): Rs. 2,699.00 incl. of all taxes',
        'Country of production: Cambodia',
        'Common generic name: Jacket',
        'Net Quantity: 1 N',
      ],
    ),
  ]);
}
